---
apiVersion: v1
kind: Namespace
metadata:
  name: pi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi
  namespace: pi
spec:
  selector:
    matchLabels:
      app: pi
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pi
    spec:
      containers:
        - name: app
          image: 'quay.io/patrickeasters/pi:latest'
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 16M
            limits:
              memory: 16M
---
apiVersion: v1
kind: Service
metadata:
  name: pi
  namespace: pi
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: pi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi
  namespace: pi
spec:
  rules:
  - host: pi.totallyfake.business
    http:
      paths:
      - backend:
          service:
            name: pi
            port:
              number: 3000
        path: /
        pathType: Prefix
